apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: k8s
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 2.41.0
  name: k8s
  namespace: monitoring
spec:
  version: 2.41.0
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus-k8s  
  enableFeatures: []
  externalLabels: {}
  image: quay.io/prometheus/prometheus:v2.41.0
  nodeSelector:
    kubernetes.io/os: linux
  podMetadata:
    labels:
      app.kubernetes.io/component: prometheus
      app.kubernetes.io/instance: k8s
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/part-of: kube-prometheus
      app.kubernetes.io/version: 2.41.0
  replicas: 2
  resources:
    requests:
      memory: 400Mi
  
  ## serviceMonitor selectors: which ones will be picked-up by this prometheus instance?
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}

  ## podMonitor selectors: which ones will be picked-up by this prometheus instance?
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  
  ## probe selectors: which ones will be picked-up by this prometheus instance?
  probeNamespaceSelector: {}
  probeSelector: {}
  
  ## prometheusRule selectors: which ones will be picked-up by this prometheus instance?
  ruleNamespaceSelector: {}
  ruleSelector: {}

  # which alertmanager instances will this prometheus instance connect to
  alerting:
    alertmanagers:
    - apiVersion: v2
      name: alertmanager-main
      namespace: monitoring
      port: web

