apiVersion: v1
kind: Namespace
metadata:
  name: podinfo-servmon
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: podinfo-servmon
  namespace: podinfo-servmon
# namespace: monitoring
  labels:
    app.kubernetes.io/name: podinfo-servmon
spec:
  endpoints:
  - path: /metrics
    # pod port name
    port: http
    interval: 15s
  # filter service namespace
  namespaceSelector:
    any: true
    # matchNames:
    # - podinfo-servmon
  # filter service labels
  selector:
    matchLabels:
      app.kubernetes.io/name: podinfo-servmon
---
apiVersion: v1
kind: Service
metadata:
  name: podinfo-servmon
  namespace: podinfo-servmon
  labels:
    app.kubernetes.io/name: podinfo-servmon
spec:
  type: ClusterIP
  ports:
    - port: 9898
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: podinfo-servmon
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo-servmon
  namespace: podinfo-servmon
  labels:
    app.kubernetes.io/name: podinfo-servmon
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: podinfo-servmon
  template:
    metadata:
      labels:
        app.kubernetes.io/name: podinfo-servmon
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9898"
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: podinfo-servmon
          image: "ghcr.io/stefanprodan/podinfo:6.3.0"
          imagePullPolicy: IfNotPresent
          command:
            - ./podinfo
            - --port=9898
            - --cert-path=/data/cert
            - --port-metrics=9797
            - --grpc-port=9999
            - --grpc-service-name=podinfo
            - --level=debug
            - --random-delay=false
            - --random-error=false
          env:
          - name: PODINFO_UI_COLOR
            value: "#34577c"
          ports:
            - name: http
              containerPort: 9898
              protocol: TCP
            - name: http-metrics
              containerPort: 9797
              protocol: TCP
            - name: grpc
              containerPort: 9999
              protocol: TCP
          volumeMounts:
          - name: data
            mountPath: /data
          resources:
            limits: null
            requests:
              cpu: 1m
              memory: 16Mi
      volumes:
      - name: data
        emptyDir: {}
